version: '3.5'

services:
  book_provider:
    image: ${DOCKER_REGISTRY-}book_provider
    container_name: "book_provider" 
    build:
      context: .
      dockerfile: BookProvider/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6005:80"
      - "6006:443"


networks:
  dev-local:
    driver: bridge
    name: dev-local