version: '3.5'
services:

  book_external_api:
    image: ${DOCKER_REGISTRY-}book_external_api
    container_name: "book_external_api" 
    build:
      context: ./BookExternalAPI/
      dockerfile: BookExternalAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  book_provider:
    image: ${DOCKER_REGISTRY-}book_provider
    container_name: "book_provider" 
    build:
      context: ./BookProvider/
      dockerfile: BookProvider/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5100:80"

  proxy:
    image: nginx:latest
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5010:80"




