version: '3.5'

services:
  bookexternalapi:
    image: ${DOCKER_REGISTRY-}book_external_api
    container_name: "book_external_api" 
    build:
      context: .
      dockerfile: BookExternalAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  proxy:
    image: nginx:latest
    volumes:
      - ./BookExternalAPI/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5010:80"

networks:
  dev-local:
    driver: bridge
    name: dev-local